/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Referenciales;

import Prg.Conexion;

/**
 *
 * @author Kiel
 */
public class Clientes extends javax.swing.JDialog {

    String vcondicion = "";
    
    public Clientes (java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Conexion.getInstanciaConexion();  //para conectar a la base de datos
        setTitle("Mantener Clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtci = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobs = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        btgrabar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("RAZON SOCIAL :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 190, 100, 15);

        txtcodigo.setEnabled(false);
        getContentPane().add(txtcodigo);
        txtcodigo.setBounds(130, 140, 90, 30);

        jLabel2.setFont(new java.awt.Font("Centaur", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CLIENTES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 10, 180, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CODIGO :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 150, 60, 15);

        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(570, 220, 290, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("C.I :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 150, 70, 15);

        txtci.setEnabled(false);
        getContentPane().add(txtci);
        txtci.setBounds(570, 140, 130, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("EMAIL :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 230, 50, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("OBSERVACION :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 300, 90, 15);

        txtrazonsocial.setEnabled(false);
        getContentPane().add(txtrazonsocial);
        txtrazonsocial.setBounds(130, 180, 320, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("RUC :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 230, 40, 15);

        txtruc.setEnabled(false);
        getContentPane().add(txtruc);
        txtruc.setBounds(130, 230, 160, 30);

        txtdireccion.setColumns(20);
        txtdireccion.setRows(5);
        txtdireccion.setEnabled(false);
        jScrollPane1.setViewportView(txtdireccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 280, 223, 83);

        txtobs.setColumns(20);
        txtobs.setRows(5);
        txtobs.setEnabled(false);
        jScrollPane2.setViewportView(txtobs);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(570, 270, 290, 90);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("DIRECCION :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 300, 70, 15);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));

        btnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(0, 153, 204));
        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnuevo.setText("NUEVO");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btmodificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(0, 153, 204));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        btmodificar.setText("MODIFICAR");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });

        bteliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(0, 153, 204));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        bteliminar.setText("ELMINAR");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btcancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 153, 204));
        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Redo_h.png"))); // NOI18N
        btcancelar.setText("CANCELAR");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btsalir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btsalir.setForeground(new java.awt.Color(0, 153, 204));
        btsalir.setText("SALIR");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnuevo)
                .addGap(29, 29, 29)
                .addComponent(btmodificar)
                .addGap(29, 29, 29)
                .addComponent(bteliminar)
                .addGap(286, 286, 286)
                .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 1210, 70);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("TELEFONO :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(490, 190, 70, 15);

        txttelefono.setEnabled(false);
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txttelefono);
        txttelefono.setBounds(570, 180, 160, 30);

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "RAZON SOCIAL", "RUC", "DIRECCION", "C.I", "TELEFONO", "OBSERVACION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbclientes);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(3, 410, 1210, 390);

        btgrabar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btgrabar.setForeground(new java.awt.Color(0, 153, 204));
        btgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        btgrabar.setText("GRABAR");
        btgrabar.setEnabled(false);
        btgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btgrabar);
        btgrabar.setBounds(980, 210, 150, 60);

        setSize(new java.awt.Dimension(1233, 843));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed

        // desactivar los botones
        Conexion.getInstanciaConexion().deshabilitar_btn(btnuevo, btmodificar, bteliminar, btgrabar);
        Conexion.getInstanciaConexion().autonumerico("id_marca", "marcas", txtcodigo);
        vcondicion = "nuevo";
        txtrazonsocial.setEnabled(true); //para habilitar txt
        txtrazonsocial.requestFocus();   // para enviar el cursos al txt
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        new Busqueda_Marcas(new JFrame(), true).setVisible(true);
        if (!txtcodigo.getText().trim().isEmpty()) {
            vcondicion = "modificar";
            Conexion.getInstanciaConexion().deshabilitar_btn(btnuevo, btmodificar, bteliminar, btgrabar);
            txtdescripcion.setEnabled(true);
            txtdescripcion.requestFocus();
        }
    }//GEN-LAST:event_btmodificarActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        new Busqueda_Marcas(new JFrame(), true).setVisible(true);
        if (!txtcodigo.getText().trim().isEmpty()) {
            vcondicion = "eliminar";
            int mensaj = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro seleccionado?", "Atencion!!", JOptionPane.YES_NO_OPTION);
            if (mensaj == 0) {
                try {
                    if (Conexion.getInstanciaConexion().obtenerRutaConeccion().getAutoCommit()) {
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().setAutoCommit(false);
                    }

                    PreparedStatement pe = Conexion.getInstanciaConexion().obtenerRutaConeccion().prepareStatement(""
                        + " delete from marcas where id_marca = ?");
                    pe.setInt(1, Integer.parseInt(txtcodigo.getText().trim()));
                    pe.execute();
                    Conexion.getInstanciaConexion().obtenerRutaConeccion().commit();
                    btcancelar.doClick();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar registro" + e);
                    try {
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().rollback();
                    } catch (SQLException ex) {
                        Logger.getLogger(Ciudades.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        txtcodigo.setText("");
        txtdescripcion.setText("");
        txtobs.setText("");
        vcondicion = "";
        txtdescripcion.setEnabled(false);
        txtobs.setEnabled(false);
        Conexion.getInstanciaConexion().habilitar_btn(btnuevo, btmodificar, bteliminar, btgrabar);
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btsalirActionPerformed

    private void btgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgrabarActionPerformed
        // si el txt esta vacio
        if (txtdescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la Descripion", "Atencion!!", JOptionPane.WARNING_MESSAGE);
            txtdescripcion.requestFocus();
            return; //ejecuta solo hasta aqui
        }

        int mensaje = JOptionPane.showConfirmDialog(null, "Desea Grabar?", "Atencion!!", JOptionPane.YES_NO_OPTION);
        //num 0 es si preisona Si
        //num 1 es si presiona No

        if (mensaje == 0) {
            if (vcondicion.equals("nuevo")) {
                // va a insertar un nuevo registro
                try {
                    //si todo esta correcto
                    if (Conexion.getInstanciaConexion().obtenerRutaConeccion().getAutoCommit()) {
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().setAutoCommit(false);
                    }
                    PreparedStatement p = Conexion.getInstanciaConexion().obtenerRutaConeccion().prepareStatement("INSERT INTO marcas(\n"
                        + "            id_marca, descripcion,obs)\n"
                        + "    VALUES (?, ?, ?);");
                    p.setInt(1, Integer.parseInt(txtcodigo.getText()));
                    p.setString(2, txtdescripcion.getText().trim().toUpperCase());
                    p.setString(3, txtobs.getText());
                    p.execute();
                    Conexion.getInstanciaConexion().obtenerRutaConeccion().commit();
                    btcancelar.doClick();
                } catch (Exception e) {
                    try {
                        JOptionPane.showMessageDialog(null, "Error al Grabar Nuevo" + e);
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().rollback();
                    } catch (SQLException ex) {
                        Logger.getLogger(Ciudades.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                //va a modificar el registro
                try {
                    //si todo esta correcto
                    if (Conexion.getInstanciaConexion().obtenerRutaConeccion().getAutoCommit()) {
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().setAutoCommit(false);
                    }
                    PreparedStatement p = Conexion.getInstanciaConexion().obtenerRutaConeccion().prepareStatement("UPDATE marcas\n"
                        + "   SET descripcion=?, obs=?\n"
                        + " WHERE id_marca=?");

                    p.setString(1, txtdescripcion.getText().trim().toUpperCase());
                    p.setString(2, txtobs.getText());
                    p.setInt(3, Integer.parseInt(txtcodigo.getText()));
                    p.execute();
                    Conexion.getInstanciaConexion().obtenerRutaConeccion().commit();
                    btcancelar.doClick();
                } catch (Exception e) {
                    try {
                        JOptionPane.showMessageDialog(null, "Error al Grabar Datos Modificados" + e);
                        Conexion.getInstanciaConexion().obtenerRutaConeccion().rollback();
                    } catch (SQLException ex) {
                        Logger.getLogger(Ciudades.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }
    }//GEN-LAST:event_btgrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btgrabar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbclientes;
    public static javax.swing.JTextField txtci;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextArea txtdireccion;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextArea txtobs;
    public static javax.swing.JTextField txtrazonsocial;
    public static javax.swing.JTextField txtruc;
    public static javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    
}
